# Generated by Django 4.2.8 on 2026-03-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('anomaly_score', models.FloatField(null=True)),
                ('prediction', models.IntegerField(null=True)),
            ],
        ),
    ]
