# Generated by Django 4.2.8 on 2026-03-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='log',
            name='data',
        ),
        migrations.RemoveField(
            model_name='log',
            name='prediction',
        ),
        migrations.AddField(
            model_name='log',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='result',
            field=models.CharField(default='Normal', max_length=100),
        ),
        migrations.AddField(
            model_name='log',
            name='xgb_prediction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='anomaly_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='log',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='log',
            name='source',
            field=models.CharField(choices=[('windows', 'Windows Event'), ('network', 'Network Packet')], default='windows', max_length=20),
        ),
    ]
