# Generated by Django 4.2.8 on 2026-03-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_log_options_remove_log_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='event_type',
        ),
        migrations.AddField(
            model_name='log',
            name='assignee',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='log',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='log',
            name='file_md5',
            field=models.CharField(default='N/A', max_length=32),
        ),
        migrations.AddField(
            model_name='log',
            name='file_motw',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='host',
            field=models.CharField(default='LPT-HR-001', max_length=100),
        ),
        migrations.AddField(
            model_name='log',
            name='name',
            field=models.CharField(default='System Event', max_length=200),
        ),
        migrations.AddField(
            model_name='log',
            name='process_name',
            field=models.CharField(default='system.exe', max_length=100),
        ),
        migrations.AddField(
            model_name='log',
            name='process_user',
            field=models.CharField(default='SYSTEM', max_length=100),
        ),
        migrations.AddField(
            model_name='log',
            name='severity',
            field=models.CharField(default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(default='Awaiting action', max_length=50),
        ),
        migrations.AddField(
            model_name='log',
            name='target_file',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='log',
            name='verdict',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='log',
            name='source',
            field=models.CharField(default='windows', max_length=50),
        ),
    ]
