# Generated by Django 4.2.8 on 2026-03-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_remove_log_event_type_log_assignee_log_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='threat_type',
            field=models.CharField(default='Unknown Attack', max_length=150),
        ),
    ]
