# Generated by Django 4.2.8 on 2026-04-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_log_threat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='block_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='log',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='blocked_ip',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='firewall_rule_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='is_firewall_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
